
name: Publish
on:
  workflow_call:    
    inputs:
      gh_user_name:
        required: true
        type: string
      gh_packages_token:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get latest tag
      id: get_tag
      run: echo "PACKAGE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Publish docker artifacts to GitHub Packages
      run: ./gradlew build publish -x test
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: ${{ inputs.gh_user_name }}
          GH_TOKEN: ${{ inputs.gh_packages_token }}

