
name: Build application
on:
  workflow_call:
    inputs:
      gh_user_name:
        required: true
        type: string
    secrets:
      packages_token:
        required: true


permissions:
  checks: write

jobs:
  run:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      env:
        GH_USERNAME: ${{ inputs.gh_user_name }}
        GH_TOKEN: ${{ secrets.packages_token }}
      run: ./gradlew build
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        annotate_only: true 
        