
name: Release new artifact version
on:
  workflow_call:
    inputs:
      dry_run:
        required: true
        type: boolean
        default: false
    secrets:
      packages_token:
        required: true

permissions:
  checks: write

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.packages_token }}
          TAG_PREFIX: v
          